config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'menus#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users,  only:   %i[index]
  resources :items,  except: %i[show]
  resources :menus,  only:   %i[index show new create]
  resources :orders, only:   %i[index new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  enum meal_type: {
    first_meal: FIRST_MEAL = 'first',
    main_meal:  MAIN_MEAL  = 'main',
    drink:      DRINK      = 'drink'
  }

  has_many :meals, inverse_of: :item, dependent: :destroy
  has_many :menus, through: :meals

  validates :name, uniqueness: true, presence: true
  validates :meal_type, presence: true
end

app/models/items_menu.rb
class ItemsMenu < ApplicationRecord
  belongs_to :item
  belongs_to :menu

  accepts_nested_attributes_for :item, reject_if: :all_blank
end

app/models/meal.rb
# frozen_string_literal: true

class Meal < ApplicationRecord
  MIN_PRICE = 0

  belongs_to :item
  belongs_to :menu

  has_many :meals_orders
  has_many :orders, through: :meals_orders

  scope :first_meals, Orders::FirstMeals
  scope :main_meals,  Orders::MainMeals
  scope :drinks,      Orders::Drinks

  accepts_nested_attributes_for :item, reject_if: :all_blank

  validates :price, presence: true, numericality: { greater_than: MIN_PRICE }
end

app/models/meals_order.rb
# frozen_string_literal: true

class MealsOrder < ApplicationRecord
  belongs_to :meal
  belongs_to :order

  accepts_nested_attributes_for :meal
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :meals, inverse_of: :menu
  has_many :items, through: :meals

  accepts_nested_attributes_for :items
  accepts_nested_attributes_for :meals, reject_if: :all_blank,
                                        allow_destroy: true

  validates :name, presence: true, uniqueness: true

  def self.today_menu
    find_by(['DATE(created_at) = ?', Date.current])
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user

  has_many :meals_orders
  has_many :meals, through: :meals_orders
  has_many :first_meals, -> { Orders::FirstMeals.call }, source: :meal, through: :meals_orders
  has_many :main_meals,  -> { Orders::MainMeals.call },  source: :meal, through: :meals_orders
  has_many :drinks,      -> { Orders::Drinks.call },     source: :meal, through: :meals_orders
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  MAX_NAME = 50
  enum role: { user: USER = 'user', admin: ADMIN = 'admin' }

  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: MAX_NAME }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def not_found
    redirect_to root_path, alert: 'Not found'
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :find_item, only: %i[edit update destroy]
  before_action :check_policy

  def index
    @facade = ::Items::Index.new
  end

  def new
    @item = ::Items::Create.call
  end

  def create
    @item = ::Items::Create.call(item_params)

    return redirect_to items_path if @item.valid?

    render :new
  end

  def update
    @item_updated = ::Items::Update.call(item: @item, params: item_params)

    return redirect_to items_path if @item_updated

    render :edit
  end

  def destroy
    ::Items::Destroy.call(item: @item)

    redirect_to items_path
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :meal_type)
  end

  def check_policy
    authorize(@item || Item)
  end
end

app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  before_action :check_policy

  def index
    @facade = ::Menus::Index.new(current_user)
  end

  def show
    @facade = ::Menus::Show.new(params)
  end

  def new
    @facade = ::Menus::NewCreate.new
  end

  def create
    @facade = ::Menus::NewCreate.new(menu_params)

    return redirect_to root_path if @facade.valid?

    render :new
  end

  private

  def menu_params
    params.require(:menu).permit(
      :name,
      meals_attributes: [
        :id,
        :_destroy,
        :item_id,
        :price,
        item_attributes: %i[id name meal_type _destroy]
      ]
    )
  end

  def check_policy
    authorize(@facade || Menu)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = ::Orders::Index.new(current_user).orders
  end

  def new
    @facade = ::Orders::NewCreate.new

    authorize @facade.order
  end

  def create
    @facade = ::Orders::NewCreate.new(current_user, order_params)

    return redirect_to orders_path if @facade.valid?

    render :new
  end

  private

  def order_params
    params.require(:order).permit(:first_meal_ids, :main_meal_ids, :drink_ids)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: %i[create]
    before_action :configure_edit_params, only: %i[update]

    protected

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    end

    def configure_edit_params
      devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = ::Users::Index.new.users
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def allowed_order?
    policy(Order.new).create?
  end
end

app/views/items/_form.haml
= simple_form_for item do |f|
  = f.input :name
  = f.input :meal_type, as: :radio_buttons, collection: Item.meal_types.keys
  = f.button :submit, class: 'btn btn-outline-success mb-2'
= link_to t('.back'), items_path, class: 'btn btn-light mt-2'

app/views/items/_item.haml
.col-md-3
  .card.mt-3
    .card-body
      %p #{item.name} (#{item.meal_type})
      = link_to t('.edit'), edit_item_path(item)
      - if facade.allowed_delete?(item)
        = link_to t('.delete'), item_path(item), method: :delete

app/views/items/edit.haml
.col-md-5.mx-auto
  %h3.text-center= t('.title')
  = render 'form', item: @item

app/views/items/index.haml
%h3.text-center= t('.title')
.row
  = render partial: 'item', collection: @facade.items, facade: @facade, locals: { facade: @facade }
= link_to t('.add_item'), new_item_path, class: 'btn btn-outline-success mt-2'

app/views/items/new.haml
.col-md-5.mx-auto
  %h3.text-center= t('.title')
  = render 'form', item: @item

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title= t('.title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    .container.mt-2
      = render 'shared/flash_messages'
      = yield
    %br

app/views/menus/_form.haml
= simple_form_for menu do |f|
  = f.input :name
  %h6.font-weight-bold= t('.items')
  #js-items
    = f.simple_fields_for :meals do |meal|
      = render 'meal_fields', f: meal
    .links
      = link_to_add_association t('.add_item'), f, :meals, class: 'btn btn-sm btn-outline-success mt-2'
    = f.button :submit, class: 'btn btn-outline-success mt-2'
= link_to t('.back'), :back, class: 'btn btn-light mt-2'

app/views/menus/_item_fields.haml
.nested-fields
  = f.input :name
  = f.input :meal_type, as: :radio_buttons, collection: Item.meal_types.keys

app/views/menus/_items_menu_fields.haml
.nested-fields
  .form-inline
    = f.association :item, collection: Item.all, prompt: t('.choose_existing_item'), label: false
    = link_to_add_association t('.create_new_item'), f, :item, class: 'btn btn-sm btn-outline-success ml-2'
    = link_to_remove_association t('.remove_item'), f, class: 'btn btn-sm btn-outline-danger ml-2'
  %hr

app/views/menus/_meal_fields.haml
.nested-fields.js-meal-fields
  .js-item-from-list
    = f.association :item, collection: @facade.ordered_names, prompt: t('.choose_existing_item'), label: false
  = f.input :price, input_html: { min: Meal::MIN_PRICE }
  = link_to_add_association t('.create_new_item'), f, :item, class: 'btn btn-sm btn-outline-success js-add-item'
  = link_to_remove_association t('.remove_item'), f, class: 'btn btn-sm btn-outline-danger'
%hr

app/views/menus/_order.haml
%tr
  %td= index
  %td= order.user_name
  %td
    %ul
      - order.meals.each do |meal|
        %li= meal.item_name
  %td= order.human_total_cost

app/views/menus/_orders.haml
%h5.font-weight-bold.text-center= t('.orders')
%table.table.table-hover
  %thead
    %th= t('.number')
    %th= t('.user')
    %th= t('.meals')
    %th= t('.total_cost')
  %tbody
    - facade.orders.each.with_index(1) do |order, index|
      = render 'order', index: index, order: order
%h6.font-weight-bold= t('.total_orders_cost')
%p.font-weight-bold= facade.total_orders_cost

app/views/menus/index.haml
%h3.text-center= t('.title')
- @facade.menus.each do |menu|
  .card.mt-2
    .card-body
      %p= menu.name
      %p= menu.human_created_at
      = link_to t('.show'), menu_path(menu)
- if @facade.allowed_create?
  = link_to t('.add_today_menu'), new_menu_path, class: 'btn btn-outline-success mt-2'

app/views/menus/new.haml
.col-md-5.mx-auto
  %h3.text-center= t('.title')
  = render 'form', menu: @facade.menu

app/views/menus/show.haml
%h3.text-center= @facade.menu_name
%h6.font-weight-bold= t('.first_meals')
- @facade.first_meals.each do |meal|
  %p= meal.meal_name_and_price
%hr
%h6.font-weight-bold= t('.main_meals')
- @facade.main_meals.each do |meal|
  %p= meal.meal_name_and_price
%hr
%h6.font-weight-bold= t('.drinks')
- @facade.drinks.each do |meal|
  %p= meal.meal_name_and_price
- if current_user.admin?
  = render 'orders', facade: @facade
= link_to t('.back'), :back, class: 'btn btn-light mt-2'

app/views/orders/index.haml
%h3.text-center= t('.title')
.row
  - @orders.each do |order|
    .col-md-3.d-flex
      .card.mt-3.w-100.border-dark
        .card-body
          %small.text-muted= order.human_created_at
          %ul
            - order.meals.each do |meal|
              %li= meal.meal_name_and_price
        .card-footer.font-weight-bold= order.human_total_cost

app/views/orders/new.haml
.col-md-5.mx-auto
  %h3.text-center= t('.title')
  = simple_form_for @facade.order do |f|
    = f.association :first_meals, collection: @facade.first_meals, as: :radio_buttons,
      label_method: :meal_name_and_price, value_method: :id
    %hr
    = f.association :main_meals, collection: @facade.main_meals, as: :radio_buttons,
      label_method: :meal_name_and_price, value_method: :id
    %hr
    = f.association :drinks, collection: @facade.drinks, as: :radio_buttons,
      label_method: :meal_name_and_price, value_method: :id
    = f.button :submit, class: 'btn btn-outline-success mb-2'

app/views/shared/_flash_messages.haml
- flash.each do |message_type, message|
  %div{ class: "alert alert-#{message_type == 'notice' ? 'success' : 'info'}" }
    %a.close{ 'data-dismiss': 'alert', href: '#' } ×
    #{message}

app/views/shared/_navbar.haml
%nav.navbar.navbar-light.bg-light.navbar-expand-lg
  .container
    %ul.navbar-nav
      %li.nav-item= link_to t('.menus'), root_path, class: 'nav-link'
      - if allowed_order?
        %li.nav-item= link_to t('.new_order'), new_order_path, class: 'nav-link'
    %ul.navbar-nav.ml-auto
      - if user_signed_in?
        - if current_user.admin?
          %li.nav-item= link_to t('.items'), items_path, class: 'nav-link'
          %li.nav-item= link_to t('.users'), users_path, class: 'nav-link'
        %li.nav-item= link_to t('.my_orders'), orders_path, class: 'nav-link'
        %li.nav-item.nav-link.active= t('.logged_in_as', user_email: current_user.email)
        %li.nav-item= link_to t('.edit_profile'), edit_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to t('.log_out'), destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        %li.nav-item= link_to t('.sign_up'), new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to t('.log_in'), new_user_session_path, class: 'nav-link'

app/views/users/index.haml
%h3.text-center= t('.title')
.row
  - @users.each do |user|
    .col-md-3
      .card.mt-3
        .card-body
          %h4= user.name
          %p= user.email